[package]
name = "symbol-search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.4", features = ["derive"] }
extend = "1.2.0"
futures = "0.3.30"
parking_lot = "0.12.3"
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.38.0", features = ["full", "io-util"] }
tokio-stream = { version = "0.1.15", features = ["io-util"] }
toml = "0.8.13"
