[fzf_settings]
preview_window = "70%"

[rust]
extensions = ["rs"]
include = [
  "entity.name.function.rust",
  "entity.name.macro.rust",
  "entity.name.struct.rust",
  "entity.name.enum.rust",
  "entity.name.module.rust",
  "entity.name.type.rust",
  "entity.name.trait.rust",
  "entity.name.impl.rust",
  "entity.name.constant.rust",
]

[python]
extensions = ["py"]
include = [
  "entity.name.class.python",
  "entity.name.function.python",
]

[go]
extensions = ["go"]
include = [
  "entity.name.function.go",
  "entity.name.type.go",

  "variable.other.constant.declaration.go - meta.block.go",
  "variable.other.readwrite.declaration.go - meta.block.go",
]

[typescript]
extensions = ["js", "jsx", "ts", "tsx"]
include = [
  "entity.name.type.class.tsx",
  "entity.name.type.alias.tsx",
  "entity.name.type.interface.tsx",
  "entity.name.function.tsx",
  "entity.name.constant.tsx",
  "meta.definition.property.tsx",
  "variable.other.constant.tsx",
]
exclude = [
  "entity.name.type.module.tsx",
  "entity.name.type.tsx",
  "meta.block.tsx",
  "meta.function-call.tsx",
  "meta.import.tsx",
  "meta.parameters.tsx",
  "meta.return.type.tsx",
  "meta.type.annotation.tsx",
  "meta.type.parameters.tsx",
]
