[fzf_settings]
preview_window = "70%"

[rust]
extensions = ["rs"]
symbols = [
  "entity.name.function.rust",
  "entity.name.macro.rust",
  "entity.name.struct.rust",
  "entity.name.enum.rust",
  "entity.name.module.rust",
  "entity.name.type.rust",
  "entity.name.trait.rust",
  "entity.name.impl.rust",
  "entity.name.constant.rust",
]
